name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.8,16.9)'
      - name: Build
        run: |
          MSBuild -p:Configuration=Release -p:Platform=x64
      - name: Create Archive
        run: |
          Compress-Archive x64\Release\*.exe,x64\Release\*.dll WinSudo.zip
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            *.zip
